name: Generate Release Notes

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install simple-git marked

      - name: Run Changelog Script
        env:
          LATEST_VERSIONS: ${{ secrets.LATEST_VERSIONS }}
        run: node ./scripts/generate-release-notes.cjs

      # Step 5: Upload Output Files as Artifacts
      - name: Upload Teams Output
        uses: actions/upload-artifact@v4
        with:
          name: output_teams
          path: ./output/output_teams.html

      - name: Upload Universum Output
        uses: actions/upload-artifact@v4
        with:
          name: output_universum
          path: ./output/output_universum.html

      - name: Update LATEST_VERSIONS
        if: success()
        env:
          GH_PAT: ${{ secrets.GH_PATH }} # Personal Access Token with required permissions
          run: |
            echo "Updating LATEST_VERSIONS secret..."
            REPO=${{ github.repository }}
            SECRET_NAME="LATEST_VERSIONS"

            # Fetch the repository's public key
            PUB_KEY=$(curl -s -H "Authorization: Bearer $GH_PAT" -H "Accept: application/vnd.github+json" https://api.github.com/repos/$REPO/actions/secrets/public-key)

            # Extract key ID and base64-encoded public key
            KEY_ID=$(echo "$PUB_KEY" | jq -r '.key_id')
            PUBLIC_KEY=$(echo "$PUB_KEY" | jq -r '.key')

            # Encrypt the secret using the public key
            ENCRYPTED_VALUE=$(echo "${{ steps.changelog.outputs.latest_versions }}" | openssl rsautl -encrypt -pubin -inkey <(echo "$PUBLIC_KEY") | base64)

            # Update the secret
            curl -X PUT \
              -H "Authorization: Bearer $GH_PAT" \
              -H "Accept: application/vnd.github+json" \
              -d '{"encrypted_value":"'"$ENCRYPTED_VALUE"'", "key_id":"'"$KEY_ID"'"}' \
              https://api.github.com/repos/$REPO/actions/secrets/$SECRET_NAME

