name: Generate Release Notes

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install simple-git marked

      - name: Run Changelog Script
        env:
          LATEST_VERSIONS: ${{ secrets.LATEST_VERSIONS }}
        run: node ./scripts/generate-release-notes.cjs

      # Step 5: Upload Output Files as Artifacts
      - name: Upload Teams Output
        uses: actions/upload-artifact@v4
        with:
          name: output_teams
          path: ./output/output_teams.html

      - name: Upload Universum Output
        uses: actions/upload-artifact@v4
        with:
          name: output_universum
          path: ./output/output_universum.html

      - name: Update LATEST_VERSIONS
        if: success()
        env:
          GH_PAT: ${{ secrets.GH_NPM_TOKEN }} # Personal Access Token with required permissions
        run: |
          echo "Updating LATEST_VERSIONS secret..."
          curl -X PUT \
            -H "Authorization: Bearer $GH_PAT" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/LATEST_VERSIONS \
            -d '{"encrypted_value":"'"$(echo ${{ steps.changelog.outputs.latest_versions }} | openssl enc -base64)"'"}'
