name: Generate Release Notes

on:
  workflow_dispatch:

env:
  LATEST_VERSIONS: ${{ vars.LATEST_VERSIONS }}

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm i

      - name: Run Changelog Script
        id: changelog
        env:
          LATEST_VERSIONS: ${{ vars.LATEST_VERSIONS }}
        run: |
          LATEST_VERSIONS=${{ vars.LATEST_VERSIONS }} node ./scripts/generate-release-notes.cjs

      - name: Upload Teams Output
        if: steps.changelog.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: output_teams
          path: ./output/output_teams.html

      - name: Upload Universum Output
        if: steps.changelog.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: output_universum
          path: ./output/output_universum.html

      - name: Update LATEST_VERSIONS Secret
        if: steps.changelog.outputs.has_changes == 'true'
        uses: mmoyaferrer/set-github-variable@v1.0.0
        with:
          name: LATEST_VERSIONS
          value: ${{ steps.changelog.outputs.latest_versions }}
          repository: smfonseca/release-notes-demo
          token: ${{ secrets.GH_PAT }}
